spring:
  cloud:
    stream:
      function:
        definition: transform;sendTestData;receive
      bindings:
        transform-out-0:
          destination: xformed
        receive-in-0:
          destination: xformed
        transform-in-0:
          destination: testtock
        sendTestData-out-0:
          destination: testtock